### ISSUE TITLE
Getting wrong checksum when downloading from SPM

### ISSUE THREAD

**Issue by casey-turczynski** [ApryseSDK/pdftron-apple-package#3]
When I try to get the latest version from the Swift Package Manager, I get this error:

fatalErrorxcodebuild: error: Could not resolve package dependencies:
  checksum of downloaded artifact of binary target 'Tools' (**06a1e9b20d958cc944a62032c3563553ef4fba848f1f510afeda51fb0ffef631**) does not match checksum specified by the manifest (**2d67ede68dbf7f36c8a2889ae442b783ea444dde1c14ba213593ecd767ac3291**)
  checksum of downloaded artifact of binary target 'PDFNet' (**3dfc366c54e3d7ef98a0286227b66f4bce46477e59591db465d35f48cf637e35**) does not match checksum specified by the manifest (**28897b563f800c340b82091f2f8e2fd0c35971dd9b39cdb485ef15f6cd13a88d**)

I have reset the caches and deleted derived data and the caches in com.apple.dt.* and org.swift.swiftpm multiple times, but am continuously met with this same error. Has this been reported before, and/or is there a known fix?

I also tried making a new project after clearing derived data and caches, and then immediately trying to add the dependency through SPM and still same result.

**Comment by gwelshonsWSH** [comment]
I am getting the same issue

<img width="1017" alt="Screenshot 2023-01-16 at 2 19 43 PM" src="https://user-images.githubusercontent.com/110043114/212759744-0ba98854-c4b2-49d4-b715-917cf6afc76b.png">

**Comment by hajjD** [comment]
Same issue still

**Comment by davidhakki** [comment]
This issue is now fixed in the latest update

**Comment by casey-turczynski** [comment]
This is still giving me the same error as originally posted when I try to add the dependency using SPM and the instructed method from https://www.pdftron.com/documentation/ios/get-started/integration/spm/, using a version range with a high max range (99.0.0). It is still grabbing version 9.4.180691. I tried just updating the package, as well as removing it, clearing derived data, and then trying to add it.

**Comment by casey-turczynski** [comment]
Apologies, after deleting the org.swift.swiftpm cache, it was able to update successfully.
Unfortunately, we are still seeing the bug where when a user taps on a signature field while the keyboard is still up for a textfield, the accepted signature is then very large and is copied on every tap.
